mozilla-iam/sso-dashboard-configuration

apps.yml

Egencia->everyone

---

apps.yml

set the heatmap prod to true for display in the dashboard.

display the prod heatmap

---

apps.yml

Various changes of okta to auth0 apps, removal of yammer

update production from master

---

apps.yml

* Restrict status page to all_moco all_mofo
* Enable airmo for everyone.
This closes out https://github.com/mozilla-iam/sso-dashboard/issues/154

Minor change to support community enablement

---

apps.yml

- people-mozilla.org
- thinksmart

Remove cruft

---

apps.yml

* Remove thinksmart and people.moz
* Fix group entitlements for thehub

Removes thinksmart fixes thehub

---

apps.yml

This is just a link but it is still an application that can be launched through the Dashboard

Adding MDN application tile

---

apps.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1405315

adding lwright to basket apps

---

apps.yml

Enable Slack for community (remove restriction)

---

apps.yml

Add dashboard data for MozDef

---

apps.yml

adding team_moc to mozdef since not all of them are in the vpn group.

add moc to mozdef

---

apps.yml

Add Box with restrictions

---

apps.yml

This resolves a bug with SN's redirect logic per https://bugzilla.mozilla.org/show_bug.cgi?id=1451865

updating servicenow url

---

CHANGELOG
README.md
apps.yml
tests/test_yaml.py

expire access after 90 days note: this is a new variable that is currently only used in dev auth0

---

CHANGELOG
README.md
apps.yml
tests/test_yaml.py

Note: the rule is NOT in prod, ie this is not doing anything until then

merge the xpiration of access to prod

---

apps.yml

add moc service accounts to tableau apps

---

apps.yml

Removed old SCL3 MozDef entries and revised the new MozDef entry to a data-center-agnostic URL

Removed old MozDef entries

---

CHANGELOG
README.md
apps.yml

This includes a setting of "LOW" TAI/AAI for Discourse

AAI and TAI support (See readme)

---

CHANGELOG
README.md
apps.yml

This adds AAI for discourse (it only works in dev) and an HRIS group for Slack (its a replacement for moco ldap groups, though im keeping both. Some people dont have the moco ldap group when onboarded...)

Merge prod

---

apps.yml

allow everyone to login to the aai low testrp

allow everyone to login to the aai low testrp

---

apps.yml

.. to match splunk's own group rules.

Adding more groups to splunk

---

apps.yml

This adds a new application to manage access to the Grafana instance for the IAM team.

adding IAM infra Grafana

---

apps.yml

@gdestuynder adds AAL LOW for discourse staging so we can QA the code there

add discourse staging with AAL LOW

---

apps.yml

closes https://bugzilla.mozilla.org/show_bug.cgi?id=1521914

add ffox secops to mozdef

---

apps.yml

We want 2FA on the ParSys Jenkins server.

Changing ParSys Jenkins to MEDIUM

---

apps.yml

restricting Jira to service_jira group

---

apps.yml

Add cloudy mozdef

---

apps.yml

Reverts mozilla-iam/sso-dashboard-configuration#265

Revert "opening up gearstore for launch at 4pm today"

---

apps.yml

Reverts mozilla-iam/sso-dashboard-configuration#266

Revert "Revert "opening up gearstore for launch at 4pm today""

---

apps.yml

(cherry picked from commit 24444bc41def2a31807f80df3d14707ea32061c2)

add service_meao_gcp ldap group to GCP Infrastructure

---

apps.yml

This pilot has been torn down so we can remove it from this side as well

Remove HackMD

---

apps.yml

@jdow decreasing etherpad security level per discussion with mhoye

decreasing security level for etherpad

---

apps.yml

Dupe of #354, now with signed commit.

Update Matrix integration to restrict authrorized groups to staff

---

apps.yml

Open up Matrix back to everyone.

Update Matrix integration to open the service to everyone

---

apps.yml

These apps no longer exists and can be removed from the config, I will leave it to you to remove the `client_id` on the auth0 side of things

Remove old applications from sso dashboard config

---

apps.yml

removing mozdatacollective

---

apps.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1627289

Grant non staff access to Project Link AWS account

---

apps.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1669663
Original PR #399 (was missing a signed commit)

Grant mozilliansorg_non-moco-sheriffs-basic access to earthangel-b40313e5.influxcloud.net

---

apps.yml

This PR will enable SSO for TripActions application. See [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1672012) for more info

Create TripActions application

---

apps.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1681831

Add experimenter stage

---

apps.yml

Remove developer-portal from sso dashboard, this project is now defunct

Cleanup dev-portal from list

---

apps.yml

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1671709

Create app for buzilla-dev.allizom.org

---

apps.yml

A request from @bhearsum who needs to grant access to a contributor to a local instance of shipit

Allow everyone to login to shipit dev

---

apps.yml

This PR will setup the access controls for Jira Cloud.
Request bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1683339

Create application for Jira Cloud

---

apps.yml

Requested in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1667833

Setup Figma application

---

apps.yml

Requested in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1594176

Reflect ValiMail configuration

---

apps.yml

Requested in bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1686056
https://bugzilla.mozilla.org/show_bug.cgi?id=1686057
https://bugzilla.mozilla.org/show_bug.cgi?id=1686058

Create Looker application: dev, stage and prod

---

apps.yml

Requested in bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1684993

Setup Slack Pocket SSO

---

apps.yml

requested in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1648253

Create app Snowflake

---

apps.yml

Removing these 2 apps as part of decommissioning the project.
Once the PR is approved, I'll remove the application in Auth0.

Remove Mozillians apps

---

apps.yml

Requested in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1683225

Setup access controls for Acoustic Stage

---

apps.yml

Requested in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1686120

Setup access control for Everest

---

.github/workflows/tests.yaml
.travis.yml
README.md

TravisCI is not anymore free for OSS projects

Use Github Actions for tests intead of TravisCI;

---

apps.yml

https://jira.mozilla.com/browse/SE-1483

mentoring app is on dotcom not dotorg

---

apps.yml

This adds a vanity endpoint and a proper login url.

Getpocket jira fixes

---

apps.yml

https://people.mozilla.org/a/basket_admin/
At pmac's request

Switch basket from ldap to mozillians

---

apps.yml

Setting url for Compiler Explorer to foxyeah.com

Setting url for Compiler Explorer to foxyeah.com

---

apps.yml

https://jira.mozilla.com/browse/IO-1790

Add relops vault application

---

apps.yml

This updates the Learnerbly app URL with the URL provided by Learnerbly.  Tested and works.

Change Learnerbly URL

---

apps.yml

Hiding jira_cloud for now

---

apps.yml

Removing gear store. [1712206]

Removing gear store. [1712206]

---

apps.yml

Removing legacy Jira and putting Jira Cloud in place

Removing legacy Jira and putting Jira Cloud in place

---

apps.yml

I got the URL wrong in the initial PR, this is the one we need.

Fix BitSight login URL

---

apps.yml

Fix broken mofo culture amp redirect URL

Fix mofo culture amp url

---

apps.yml

Adding client_id for compiler explorer.

---

apps.yml

This pull request attempts to fold in the changes discussed in bug 1722018.

apps: Update groups, display, url for salescloud_np [#1722018]

---

apps.yml

Hi, SSO Dashboard apps.yml PR reviewers.
I'm looking to confirm that this documentation change is clear and understandable, and that it makes sense to everyone. It's been through a couple rounds of internal review before PR, and if there are no blocker objections uncovered in this final set of review requests, I'm going to ship it to close IAM-886.
I've requested review from all current apps.yml reviewers, both primary (websre west) and last-resort/standby/concerned-bystanders. If you take the time to review this documentation-only update, I would absolutely appreciate it, and if your time doesn't permit, I understand and it's fine.

docs: add tiles show/hide explanation to apps.yml

---

apps.yml

@sciurus This will require the `contentful-access` group to be created first.

Change access for Contentful to a people.m.o group

---

apps.yml

Add admin role accounts to Box [#1729527]

---

apps.yml

add settings.dev.mozaws.net(kinto-dev) app

Apps: add settings.dev.mozaws.net(kinto-dev) app

---

apps.yml

Removes Syntrio from the dashboard as requested

Remove Syntrio from dashboard [#1729047]

---

apps.yml

https://mozilla-hub.atlassian.net/browse/SEC-2830
Please also delete the `snpYGrMjpcnNlz7FlXxgFs9ok7IRz83g` client from Auth0

Remove ASAP RP as it's decomissioned

---

apps.yml

[SE-2947](https://mozilla-hub.atlassian.net/browse/SE-2947)
https://bugzilla.mozilla.org/show_bug.cgi?id=1743115

Add new callback URL for Kinto DEMO

---

apps.yml

This PR simply adds the Pocket instance of Sentry.io

Add sentry.io (Pocket) app [1750795]

---

apps.yml

https://mozilla-hub.atlassian.net/browse/DSRE-653

Add authorization for protosaur.dev

---

apps.yml

add modernhealth [1757773]

---

apps.yml

Add paradigmreach [1757460]

---

apps.yml

hide paradigmreach, modernhealth until they are confirmed working

---

apps.yml

Update splunk RPs groups

---

apps.yml

To be deployed tonight EOD per discussion with service owner.

enable paradigm tile

---

apps.yml

logikcull requires us to initiate through their site

---

apps.yml

Per action item 1 in [comment #9](https://bugzilla.mozilla.org/1637172#c9)

Bug 1637172 - Remove all `hris_is_staff` rules from apps.yml

---

apps.yml

Grant team_mzla the same permissions as team_mofo, as part of onboarding MZLA-of-MoFo with the same access as MoFo.

Copy all team_mofo permissions to team_mzla

---

apps.yml

Related ticket : https://bugzilla.mozilla.org/show_bug.cgi?id=1766900

Add Pocket Snowplow

---

apps.yml

CC: @floatingatoll @bkochendorfer for review, thx!

enable greenhouse for team_mzla

---

apps.yml

This one can be deployed once reviewed.

add netops to splunk ES/SC [#1779061]

---

README.md

Also, wrap text so that it's possible to more easily see what's changing (instead of any change in a section showing the entire section changing)

Add details to README about CI process

---

apps.yml

Allows `team_mzla` access to zoom

Allow zoom access for team_mzla [SE-3304]

---

apps.yml

This PR grants access to Google Workspace apps for team_mzla

Grant team_mzla access to Google Workspaces [SE-3319]

---

apps.yml

cc @moz-hwine Here's the change you requested. (second PR as the first one had a mistake)

Hide the riskheatmap on the dashboard

---

apps.yml

Fix acryl url

---

apps.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1795163

Allow zoomadmin to access jira, bug 1795163

---

apps.yml

This is a correction from #628 based on new information.
#634 was this, but not signed.

Add zoomadmin to JSM, 1795163

---

apps.yml

Enable team_mzla access to Slack

---

apps.yml

Adds MZLA access to Panopto (Air Mozilla)

Add MZLA to Panopto [IAM-1008]

---

apps.yml

Please confirm in IAM-1057 that it's OK to proceed with the owners, and that all listed Auth0 applications have been removed, before committing and releasing.
(HOLD until 1/31)

remove legacy PTO apps [IAM-1057]

---

apps.yml

for https://bugzilla.mozilla.org/show_bug.cgi?id=1814102

Add fuzzmanager-staging

---

apps.yml

https://mozilla-hub.atlassian.net/browse/IAM-1077

Give Team MZLA access to Navan/TripActions

---

apps.yml

https://mozilla-hub.atlassian.net/browse/IAM-1075

rm cloudsnap

---

apps.yml

https://mozilla-hub.atlassian.net/browse/IAM-1074

rm fxa-support-panel

---

apps.yml

https://mozilla-hub.atlassian.net/browse/IAM-1051

Remove old mana stage

---

.gitignore
apps.yml

IAM-1049: this removes security wiki tile from dashboard.

decomm security wiki from apps.yml

---

apps.yml

IAM-1048: this removes the Uptycs tile from the dashboard.

uptycs decomm

---

apps.yml

This PR adds an entry for donate-wagtail.mofostaging.net

Add app for donate-wagtail.mofostaging.net [IAM-1084]

---

apps.yml

This PR adds new entries for balrog prod/stage/dev

Add new balrog entries [IAM-1070]

---

apps.yml

Include mozilliansorg_pocket_backend in new-relic-sre

---

apps.yml

iam-1068, removed decommissioned  moziilian  app.

iam-1068 removed old mozillians app

---

apps.yml

This PR adds entries for the dev and prod instances of the Auth0 user management app

Add entry for Auth0 user management app [IAM-1122]

---

apps.yml

allowed team_mzla into app coderpad
https://mozilla-hub.atlassian.net/browse/IAM-1115

edited access for coderpad

---

apps.yml

Add Swoogo entry [IAM-1103]

---

apps.yml

Update URL and title for dbt Cloud

---

apps.yml

IAM-1130. removed old moderator app and updated vanity url to duplicate moderator app

removed moderator and updated vanity url

---

apps.yml

IAM-1147, enabled team_mzla access into Udemy app.

allowed team_mzla into udemy

---

apps.yml

Adds supabase
https://bugzilla.mozilla.org/show_bug.cgi?id=1837672

Add supabase

---

apps.yml

This PR updates the balrog admin stage URL

Update Balrog admin stage URL

---

apps.yml

IAM-1174
updated URL for Recorded Future

updated URL for Recorded Future

---

apps.yml

Removes the dup entry for New Relic IT SRE

Remove duplicate entry for New Relic SRE

---

apps.yml

IAM-1192, created bird-development app

added birdbox-development

---

apps.yml

fixed Dualo URL in apps.yml

---

apps.yml

Add rapid7_access per request

---

apps.yml

IAM-1220, added 3 Mozilla Social apps

added 3 MoSo apps

---

apps.yml

IAM-1224 added 2 pocket groups to their aws app

added 2 groups to pocket AWS SSO

---

apps.yml

Add service user per IAM-1222

---

apps.yml

IAM-1224, edited Pocket AWS billing group

edited pocket aws billing group

---

apps.yml

IAM-1238 - added Cinder app for stage and prod

added cinder app for prod and stage

---

apps.yml

HOLD/WIP: Stage app entries for IAM-1231

---

apps.yml

Remove Pocket Slack and Jira

---

apps.yml

Remove three retired Salesforce entries

---

apps.yml

updated user group for remote.com

updated authorized group remote.com

---

apps.yml

fixed url and added vanity url

---

apps.yml

IAM-1278 URL updated after testing with requester.

fixed URL and name for prefect

---

apps.yml

IAM-1284 decommissioned MAWS auth0 app

decom MAWS auth0 app

---

apps.yml

IAM-1288: Recorded Future TI

---

apps.yml

IAM-1278 updating login url after meeting with prefect dev team

updated url for prefect

---

apps.yml

adding cloudpay to sso dashboard

---

.github/workflows/google-deploy.yaml
Makefile

This causes the s3 and gcs to also get the images folder uploaded.

Make sure to upload the images folder also.. duh

---

apps.yml

IAM-1301, updated authorized groups for splunk

updated authorized groups for splunk

---

Makefile

I've tested this aws s3 sync and it works

Upload images to the correct s3 prefix

---

apps.yml

IAM-1311 changes access groups on the recorded futures apps

---

apps.yml

Add MZVC and MZAI to Navan and Jira Service Management [IAM-1318]

---

apps.yml

IAM-1322, added miniOrange app.

added miniOrange app

---

apps.yml

IAM-1332: updated Salescloud app name to MoFo Salesforce

updated salesforce/salescloud app name

---

apps.yml

IAM-1339 adding common room app to dashboard.

added common room app to dashboard

---

tools/client_id_checker.rb

Update clientid tool

---

apps.yml

IAM-1348: added Skylight - [prod,dev] app

added skylight prod/dev app

---

apps.yml

IAM-1349 updating tile URL per vendor. Testing has been done with Mark/:freshness.

updated chatgpt URL

---

apps.yml

IAM-1348: updated authorized_groups to team_moco

updated authorized_groups to team_moco

---

apps.yml

IAM-1348 updated dashboard URL

updated skylight-prod URL

---

apps.yml

Adds one-time exception for travel account

---

apps.yml

IAM-1350, added Bedrock CMS apps - prod, stage, dev, local dev

added 4 Bedrock CMS apps

---

apps.yml

IAM-1360: added new authorized group to Asana app

added new authorized group to Asana app

---

apps.yml

IAM-1371: added a new vanity URL for Asana app.

added a vanity url for asana

---

apps.yml

IAM-1373: added 2 new groups to Cloudservices's AWS app

added new groups to cloudservices aws app

---

apps.yml

IAM-1378: added 2 access groups to grafana influx app earthangel.

updated access group for grafana influx app

---

apps.yml

Add entry for Nemo Grafana

---

apps.yml

This reverts commit 1045d0bc211e41ff3ed2851a7cbb6c761dfff929.

Puts back fixed Slack Enterprise app

---

apps.yml

https://mozilla-hub.atlassian.net/browse/IAM-1374?focusedCommentId=916644

Change MLP tile name per request

---

apps.yml

IAM-1400: added a test group for ...testing.

added a test group to udemy mofo app

---

apps.yml

removed test group from udemy mofo

---

tests/test_yaml.py

A deeper inspection of `apps.yaml` and trying to look for errors.  The regex's are tight (possibly too tight) but if they are then we can expand them in the future.

Add richer tests for YAML parsing, IAM-1399

---

apps.yml

Restore nagios entry with new client id

---

apps.yml

Bug 1912134: add Elastic SSO Validation entry

---

apps.yml

added bigeye app

---

apps.yml

IAM-1415 added fakespot elastic app

added fakepsot elastic app

---

apps.yml

IAM-1421: added webcompat fuzzing app

added new webcompat fuzzing app

---

apps.yml

IAM-1438: removed 3 MoSo apps - local dev, stage, prod.

removed MoSo apps

---

apps.yml

added fable app

---

apps.yml

feat(cloudservices-aws): Grant Billing access to aws_billing_access

---

apps.yml

IAM-1465: added a vanity URL for Smartling app.

added vanity url for smartling app

---

apps.yml

IAM-1533: decommissioned application Deleteme

decommissioned deleteme

---

apps.yml

updated URL for testrail tile

---

apps.yml

IAM-1542: added team_mzla to two apps - remote.com and small-improvements

added team_mzla to remote.com and small-improvements apps

---

apps.yml

added fleet app

---

apps.yml

IAM-1546: updated URL for fleet

updated URL for fleet app

---

apps.yml

IAM-1559: added an access group for Wiz

updated access groups for Wiz

---

apps.yml

Cleanup per IAM-1547

---

apps.yml

IAM-1563: added Fastly NextGenWAF app

added fastly nextgenwaf app

---

apps.yml

IAM-1566: added FleetDM app and enabled tile for Fleet (different apps)

added fleetdm app and enabled fleet tile

---

apps.yml

Update MoFo-specific app titles for IAM-1575

---

apps.yml

IAM-1578: adding team_mofo to Fable App

added team mofo to fable app

---

apps.yml

IAM-1582: deleted peacefulstream app

deleted app peaceful-stream

---

apps.yml

IAM-1462: updated client ID for Matrix/Element chat

updated element/matrix client ID

---

apps.yml

fixed group names in wiz

---

apps.yml

removing everbridge members tile visibility until app is ready.

removed tile visibility until app is ready

---

apps.yml

Jira: [SE-4389](https://mozilla-hub.atlassian.net/browse/SE-4389)

New group (mozilliansorg_fakespot_mturk_developer) of devs

---

apps.yml

IAM-1602: added Ethyca stage and prod to dashboard.

added ethyca stage and prod app

---

apps.yml

IAM-1603: adding Mozilla Language Portal Staging/Production to dashboard.

adding mozilla language portal stage and prod to dashboard

---

apps.yml

IAM-1606: decommissioned 3 InfluxDB apps. Validated by Nate.
https://docs.google.com/spreadsheets/d/14Ve7n0RW3x1hQLNxPh9Vp6w-TKSC0_IdHgIUq-gcnes/

decommissioned influxdb apps (3)

---

apps.yml

Jira: [IAM-1448](https://mozilla-hub.atlassian.net/browse/IAM-1448)

Add new yardstick app

---

apps.yml

Jira: [IAM-1608](https://mozilla-hub.atlassian.net/browse/IAM-1608)

Successful logins would result in redirection issue

---

buildspec.yml

Totally forgot this isn't deployed using GitHub, but AWS CodeBuild. This pushes the yml files to infosec accounts.
Jira: [IAM-950](https://mozilla-hub.atlassian.net/browse/IAM-950)

build Missing python requirements, and an outdated Python version

---

apps.yml

IAM-1633: decommissioned Xmatters and Xmatters Stage

decommissioned xmatter and xmatter stage

---

apps.yml

added pingdom app

---

apps.yml

IAM-1631: added a second Crashplan app and called it Crashplan 2 per Jenny Hung.

added crashplan 2

---

apps.yml

Remove r7 and soar

---

apps.yml

IAM-1646: new required Navan integration.

adding new Navan integration

---

apps.yml

add Firefox-AI - IAM-1671

---

apps.yml

IAM-1686: added new test app for Firefox enterprise console.

added new test app for FF enterprise console

---

apps.yml

Udemy MZLA (IAM-1693)

---

README.md

typo in readme affecting prod deployments

---

apps.yml

Testing new deployment with Bhee

adding a test vanity URL

---

apps.yml

fix(iam): Remove duplicate dinopark staging

---

apps.yml

IAM-1776: Added Lattice Sandbox app

adding Lattice Sandbox app

---

apps.yml

IAM-1801 and IAM-1800: renamed Fleet app to Fleet Prod and added a Fleet-Stage app.

added new fleet stage app and renamed Prod
