mozilla-iam/sso-dashboard-configuration

apps.yml

Gmail is the correct spelling, not G-Mail
Google Drive and Google Calendar are also the correct product
names/spellings
Yammer was rendering as O365 because that is the authentication method
they are leveraging, but not the product Mozilla employees will see.

Fixed Naming for Google Products and Yammer

---

apps.yml

Changed from discourse.mozilla-community.org to discourse.mozilla.org

Updated Discourse URL

---

apps.yml

This will put the new and old Air Mozilla icons next to each other on the dashboard. It's not necessarily obvious at first glance that the Legacy air.mo is available anymore.
Thanks!

Rename "Legacy Air Mozilla" to "Air Mozilla (Legacy)"

---

apps.yml

This will put …the two air.mo icons next to each other. (#133)

Rename "Legacy Air Mozilla" to "Air Mozilla (Legacy)". 

---

apps.yml

because multiple egencia apps exist with the same client ID, the access control isn't working right for it.

removing client ids from egencia

---

README.md
apps.yml

i just realized this wasnt using the stuff we spec'd
AAL is the level (LOW MEDIUM HIGH MAX..)
AAI is the array of authentication assurance proofs/indicators (2FA, HIGH ASSURANCE, GEOLOC, etc)
This fixes the wording basically

s/AAI/AAL/ which is the correct word..

---

apps.yml

This adds a new application for Grafana. It is currently pointing at Auth0 dev until we test this. When it is working as intended, I can ask for a prod app and I can update the client ID.

adding IAM infra Grafana

---

apps.yml

This is a follow up to #204. This PR provides the correct client ID.

setting proper OIDC client ID for Grafana

---

apps.yml

* Adds all apps with LDAP-only or with at least passwordless login methods
to the list
* Adds `AAL=LOW` to all apps which have passwordless already enabled, so
that it continues functioning with deratcheting enabled
* Adds `everyone` group when no authorized user or groups are present (emulate old functionality)
* Adds `authorized_groups += ['team_moco', 'team_mofo', 'hris_is_staff']` to all clients with LDAP-only so that the LDAP-only
restriction is still enforced after all login methods are enabled for the
RP
NOTE: This list has been re-serialized by PyYAML as this is the output of a
script which compared entries in Auth0.

 Support for deracheting/AAL

---

apps.yml

* Removed unused signoff.shipit.staging.mozilla-releng.net
* Added the `vpn_cloudops_shipit` LDAP group to
`application.authorized_groups` for shipit (prod and staging). Ship-it
performs additional checks in order to use refined permissions.
Additionally the API backend allows only IP addresses from the
`vpn_cloudops_shipit` VPN IP addresses.

Bug 1558957: adjust shipit groups

---

apps.yml

Relates to mozilla-iam/auth0-deploy#288

Change access to iam-infra from mozillians group to LDAP group

---

apps.yml

The Mozilla IRCCloud instance has been decommissioned
for just under a month now. Time to remove it from the
dashboard.

apps: remove `IRCCloud` as an app on the dashboard

---

apps.yml

This will prevent the EIS New Relic tile from showing up on the SSO Dashboard for all of moco (as only EIS can actually access it, everyone else would get an access denied from NewRelic)
Followup to #339

Change EIS New Relic group from moco to EIS

---

apps.yml

Deleted Smartsheets and Proofpoint "Security Awareness Training" as smartsheets is EOL and proofpoint is not renewed.

Remove Smartsheet and mozilla.securityeducation.com mozilla.wombatsecurity.com from apps.yml

---

apps.yml

Without a logo, the build fails.
Choosing mozillians logo because Vouches is part of Mozillians

Add logo to vouches app

---

apps.yml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1677158

Expand AWS SSO access to non staff in mozillians group searchfox-aws

---

apps.yml

This PR will remove the configuration for Mattermost and RocketChat which are not used.
I'm holding until mhoye confirms I can proceed.
Afterwards, I'll delete the applications in Auth0.

Remove unused apps

---

apps.yml

This PR will delete all the occurrences of Phonebook in the configuration.
I've also deleted the respective apps in Auth0 for all applications but `o2e391VjmnPk0115UedNTmRL8x2nySOa` as I'm not sure if that can go.
Please @fiji-flo can you confirm you are not using that one but `o2e391VjmnPk0115UedNTmRL8x2nySOa`?

Cleanup references to old phonebook deployments

---

apps.yml

Remove duplicate configuration for netlify and also limits netlify access to a specific user group.
This PR resolves part of the issue stated in issue https://github.com/mozilla-iam/sso-dashboard-configuration/issues/348

Limit access to netlify to just netlify_access group

---

apps.yml

As a followup to #435, which doesn't include the other three telemetry related services as confirmed by @jasonthomas in https://bugzil.la/1693956#c4 .
I'm not sure which one of "GLAM" or "GLAM (prod)" is the right one, so updated them both.
r?@The-smooth-operator
Thanks!

Grant MozillaOnline employees access to telemetry services (cont'd)

---

apps.yml

The existing URL doesn't log the user in. Replacing it with the login URL
Updates #409

Fix tripactions URL

---

apps.yml

Given that all members of team_pocket are now members of team_moco and the purpose of
the team_pocket group has changed, this commit removes those references to
team_pocket except in cases where it is explicity granting access to only the members

Remove team_pocket from apps

---

apps.yml

We'll need the `snippets_admin` and `nucleus_admin` groups created on people.m.o first, but I think this should do it.
/cc @sciurus @duallain

Switch Snippets and Nucleus to Mozillians group

---

apps.yml

This deduplicates the culture amp config and makes it visible to all employees as requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1700222

[DO NOT MERGE BEFORE 4/19] Make culture amp available to everyone

---

apps.yml

This PR was opened per @ForgottenSonata's comment at [bug 1710783](https://bugzilla.mozilla.org/show_bug.cgi?id=1710783#c2).
r?@sciurus

Bug 1710783 - Grant MozillaOnline employees access to Figma.

---

apps.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1713035
This PR sets up a new SAML application to supersede the AdZerk application.  Once Kevel applies the SAML metadata to their side and we can verify the SSO works on our side, I will then submit a follow up PR to remove the deprecated AdZerk application.

Add application for Kevel [Bug 1713035]

---

apps.yml

This is cleanup for an app that has already been decomissioned
https://mozilla-hub.atlassian.net/browse/SE-1771

Remove mentoring.mozilla.com

---

apps.yml

This PR adds the Mofo specific culture amp account.  Note: culture amp has not yet configured their side so URL probably won't work until it is.

(Do not merge until culture amp finish setup) Add mofo culture amp application [bug 1717822]

---

apps.yml

This PR adds a dashboard application for an existing auth0 app.  It was discovered that the lando staging app had a dashboard app but the dev did not.  This fixes that.
See bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1720522

Add lando.devsvcdev.mozaws.net dashboard app - Bug [1720522]

---

apps.yml

As requested by MozillaOnline in [bug 1724131](https://bugzilla.mozilla.org/show_bug.cgi?id=1724131), grant them access to GetAbstract and Udemy as well.

apps: add MO to getabstract and udemy [#1724131]

---

apps.yml

Round two. It turns out we have three Expensify instances, and so there's probably something broken between them. We'll add the billing@ user to all three.

Add the billing user to all expensify instances [SE-2440]

---

apps.yml

As requested by Jen, display Everfi to all users.

apps: enable Everfi tile display in dashboard

---

apps.yml

Confirmed via slack, `moco` is the only group that should have access.

Internal Pocket Admin Tools [#1730268]

---

.github/pull_request_template.md

The GitHub UI can make it seem like selecting a reviewer is mandatory, but we've got that covered.

add a PR template note about default reviewers

---

apps.yml

This PR adds the looker (People) instance to the SSO dashboard.  This needs to be in place before completing the SAML configuration in the looker instance in order to prevent unauthorized access.
https://mozilla-hub.atlassian.net/browse/IAM-912

Looker people [IAM-912]

---

apps.yml

This PR removes several instances of decomm'ed service now instances.  Both this PR and the removal of the matching Auth0 RPs are pending removal confirmation in the bug 1745856.

Remove decommed service-now instances [1745856]

---

apps.yml

Client `GbOYKyYEIIfgu34Aq2ykl8vTnGfQ28aq` has been deleted in auth0 since it's no longer used. This also adds a new app for Splunk SOAR.

Replace splunk dev with splunk soar application

---

apps.yml

Authentication for Status Page was integrated directly into Atlassian hub. Since we use auth there we no longer need a separate login or application for status page. This points directly at the management page for our account.

chore(statuspage): Update URL for Status Page

---

apps.yml

We're going to suspend the access while we migrate users, so that they don't suddenly see a full dashboard of new SSO apps that we haven't tested or setup integrations for yet (such as GApps and Zoom). We'll undo this piecemeal later as testing permits.

temp disable mzla for live migrations

---

apps.yml

This is a 2-piece PR:
Commit 1 removes a superfluous definition of ldapadmin1's phpldapadmin configuration that shouldn't have been in place.  This was discovered in the process of researching this work.
Commit 2 makes a clone of the real phpldapadmin configuration, aiming it at a new server.  Once service work is completed, the old instance will be removed.

Update phpldapadmin configurations [SE-3246]

---

apps.yml

This group addition comes from work to support https://mana.mozilla.org/wiki/display/SECURITY/Security+Precautions+when+traveling - wherein we want to give users going into high-infosec-threat countries a temporary user who can do minimal tasks.
In this case, the list was settled at to be Zoom, Slack, gmail/gcal/gsuite.  This list was reviewed by EUS to be the minimum needs to start from.

Add travelling_accounts group to support users made for high-threat travel

---

apps.yml

Dupe of #612, but with signed commits, sorry.
This is a followup to #611 .
Commit 1 removes the dupe created in that PR; Commit 2 changes our URL to the host instead of the long ugly SAML URL, as I have pivoted from SAML to OIDC on ldapmanager1.

Cleanup of phpldapadmin entry [SE-3246]

---

apps.yml

The office support folks (currently receptionists + mailroom) are currently
manually misclassified as team_moco to get them access to essential tools.
In order to remove such forced errors and their knock-on effects, I've created
a group for them to belong to, so that they may be only get what access
their roles require.

Add office support staff to apps they need. IO-2052

---

apps.yml

Per an odd request, we'd like to have a group of users who
* aren't team_moco / other autogroup members,
* can access gmail
* can't access gcal/gdocs.
... and here we are.

Add team_gmail_only to access gmail

---

tools/image_reconcile.py

Whipped up a python tool to do the comparison of `apps.yml`'s `logo` fields vs the contents of `images`.
Intended to be pretty portable across OSX's `python` and older Linux's `python3`.

Add tool to find apps.yml logo discrepancies, IAM-1063

---

apps.yml

A redo of https://github.com/mozilla-iam/sso-dashboard-configuration/pull/505 due to age/conflicts/etc.
> While working on SE-2440 we noticed that complicated SSO entries are spread out throughout the file. This PR attempts to improve that somewhat and includes comments from our analysis and intentions.
> 
> This should have zero functional changes to any service listed, and I did my best to retain the ordering in case that's secretly relevant.

Redo: Group certain complicated SSO entries together [SE-2440]

---

apps.yml

So that sfomailroom can access the service, as well as other members of that group if they're added to the service later.

Adds team_office_support to Box

---

apps.yml

It was reported that the Moderator tile isn't visible on the dashboard. Sure enough, it's `display:` was set to `false`, this sets it to `true`.
I believe that this is a side-effect of the recent cleanup Van did which might have included a different Moderator tile which was visible, and somehow in all of that it got flipped false.

Make the Moderator tile visible

---

apps.yml

This PR swaps the IDs used for Prod and Stage.  It matches reality due to some changes made on the SP side.  This  change is mostly to makes sure the vanity urls match properly to their respective environments.

Swap khoros client IDs

---

apps.yml

This updates the sso.allizom.org client ID to properly match the client application in the Auth0 dev tenant.

Update sso.allizom.org client ID

---

apps.yml

This changes the access control for BitSight so that it matches that access control used within the BitSight vendor. This way a user only need be added to, for example, the `bitsight-users` people.mozilla.org access group to get access to BitSight (instead of how it works currently where the user needs to be a member of both `bithsight-users` in people.mozilla.org and `team_opsec` in LDAP)

Update BitSight access control

---

.github/workflows/google-deploy.yaml
.github/workflows/payload-slack-content.json

This PR causes the github actions to send slack notifications when deploying to google cloud storage.

Send slack notifications on deployments to google cloud storage

---

apps.yml

While reviewing for another task, I noticed two apps that have invalid client_ids. I don't have context for their decom bugs, but here's a PR to remove them from apps.yml for the team to review and merge.

remove two decommissioned auth0 apps

---

.github/workflows/payload-slack-content.json

From last build:
```
Run slackapi/slack-github-action@v1.24.0
[WARN]  web-api:WebClient:0 The top-level `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message. The `text` is used in places where the content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
[WARN]  web-api:WebClient:0 Additionally, the attachment-level `fallback` argument is missing in the request payload for a chat.postMessage call - To avoid this warning, it is recommended to always provide a top-level `text` argument when posting a message. Alternatively, you can provide an attachment-level `fallback` argument, though this is now considered a legacy field (see …
```

Add top-level text argument

---

apps.yml

This PR adds an entry for the dev instance of the sso dashboard.  Most importantly it sets the AAL to `LOW` which matches the prod instance.

Add entry for sso.allizom.org dashboard

---

apps.yml

Grants iam team access to green sre team new relic so they may access IAM monitoring.

Add iam-project group to websre newrelic IAM-1253

---

apps.yml

Removes the decommed Pocket Expensify entry and a redundant entry for the primary one.
IAM-896

IAM-896: Expensify apps.yml entries are not in a valid state

---

.github/workflows/google-deploy.yaml
Makefile

This PR changes the uploading of apps.yml.  We no longer sync the entire directory and instead only upload the `apps.yml` file.  We also apply the `Cache-Control: no-cache` header to the object.

Upload only apps.yml and set cache control on objct

---

.github/pull_request_template.md

Update the PR template quickref for new integrations, to check that Auth0 connections enable only LDAP and not other methods.

add a note about auth0 ldap-only

---

apps.yml

updated authorized groups to team_moco

---

apps.yml

IAM-1279 removing references to pocket for Braze app and added new authorized groups.

updated braze app with new group and name

---

apps.yml

https://bugzilla.mozilla.org/show_bug.cgi?id=1886211

Add Webcompat Dashboard (dev)

---

apps.yml

IAM-1279 removed Braze-Pocket group from authorized_groups

removed old braze-pocket group

---

apps.yml

IAM-1314. WX wanted to keep the old Swoogo SSO just in case for another few weeks. Renamed old Swoogo app to Swoogo 2023, new Swoogo app is named Swoogo 2024 for easier identification. Name changes are reflected in auth0.

adding swoogo 2024 for all hands registration

---

apps.yml

IAM-1314: removed Swoogo 2023 - last year's all hands registration

removed Swoogo 2023 from apps.yml

---

apps.yml

Adds a couple of vanity URLs that I guess incorrectly every time.

Add /gcal and /jsm vanity URLs

---

apps.yml

To hopefully address the issue with a travel account exception.

Adds temp travel user to all Jira entries with matching client_id

---

apps.yml

We are in a limbo state where Security has begun allowing travelling accounts to access Jira as one-offs, but at the same time we don't have a solid policy on allowing EVERY travelling account to access Jira.  This is a stand-in group so that we can easily allow this.  If a policy change happens, we can `s/_jira//` later.
(No issue on file, this stems from verbal discussions)

Add LDAP group travelling_accounts_jira

---

apps.yml

The "Balrog (prod)" url points to the wrong place, and "Balrog (dev)" hasn't been running for a long time.

fix: update balrog prod url and remove balrog dev

---

.github/workflows/google-deploy.yaml
.github/workflows/tests.yaml
Makefile
tests/test_yaml.py

This PR updates versions for various third party Github Actions, the python version for unittesting, and `pyyaml` version used in the unittest.

Bump versions for GHA modules and unittests

---

apps.yml

https://mozilla-hub.atlassian.net/browse/IAM-1367

Grant infrasec access to Pocket AWS SSO

---

apps.yml

add infrasec per IAM-1358

---

apps.yml

They require SP-initiated SSO, thus updating the url.

Update LifeLabs URL

---

.github/workflows/payload-slack-content.json

I noticed that ~`env.GITHUB_ACTOR`~ `env.RELEASE_NAME` is always `???` so I tossed that. Reordered the text fields a little, and made the values bold. And moved the workflow name to the empty text field spot.

Slack payload message tweak

---

.github/workflows/payload-slack-content.json

Moves `env.GITHUB_REPOSITORY` back to the first column where it shouldn't line wrap, removes the markdown for bold text on the `plain_text` fields, but updates the `env.GITHUB_REF_NAME` field to `mrkdwn` so I can bolden the tag name.

Update Slack payload message (take 2)

---

apps.yml

IAM-1384 Add Developer Services group to Cloudservices AWS SSO

---

apps.yml

IAM-1389 Add FxA developers to Cloudservices AWS

---

apps.yml

Omitted 'Grid' from the name since it will probably get cut-off and look like "Slack Enterprise Gr...", also it's not super relevant for end users.
This will let me gate access to just Michele and I while I get SSO ready for the migration.

Initial entry for Slack Enterprise

---

apps.yml

And stage the remaining groups (commented out) for when the time comes to switch.

Switch to using a group for early access

---

tests/test_yaml.py

Update test cases for `vanity_url` IAM-1399

---

apps.yml

IAM-1375
This removes the `IntranetWiki` group and replaces it with a swath of teams, with the intention being "all employees".  There's history in that bug.
Nitpick note: `team_mozillaonline` and `team_mozillajapan` are empty/useless nongroups, but are kept as parallels to other "every employee" debris in other entries for detection later ("THESE mean EVERYONE").  It might be an anti-pattern but short of putting in formal effort of removing those entirely, I'm following the current pattern.

Replace IntranetWiki group with a raft of teams, IAM-1375

---

apps.yml

This PR is the first step to the Slack migration.  It removes the old slack app, adds the vanity url to the new app and set the tile to display.   Before this PR is deployed to production, the old client will need to be deleted from Auth0.
old client_id: `WXVdgVoCca11OtpGlK8Ir3pR9CBAlSA5`

Remove old slack app, add vanity to new app, and display

---

apps.yml

Migration is complete.  This enables access to slack for the full org.

Enable org access to slack enterprise

---

CHANGELOG
README.md
tests/test_yaml.py

Remove `expire_access_when_unused_after`, IAM-1267

---

apps.yml

These are pretty obvious decom'ed apps.

Remove silly+obviously-decom'ed applications from apps.yml

---

apps.yml

Concomitant with https://github.com/mozilla-iam/aws-iam-identity-center-management/pull/6

Add infrasec to AWS - IT

---

apps.yml

IAM-1385: removed asana-marketing-access from asana app

removed asana-marketing-access from asana app

---

apps.yml

IAM-1401, updated URL for FundRaise Up. Per their docs, they do not recommend IdP initiated logins.

updated URL for fundraiseup

---

apps.yml

IAM-1420: updated authorized groups for testrail to include team_mzla and testrail-access

updated authorizzed groups for testrail app

---

apps.yml

There are a large handful of managers who need SSO access who aren't already in `team_moco` or `team_elance`, so this group is for them.

Add lifelabs-access group for edge cases per IAM-1374

---

apps.yml

Decom sccache per IAM-1396

---

apps.yml

Add team_mzla to zendesk, verbal request in servicedesk

---

apps.yml

This reverts commit 2df64a47aedf5edf07583c9a6702ed64e8a5f348.
MZLA can't have access to zendesk without a direct agreement, the current contract is insufficient for partner access.

Revert "Add team_mzla to zendesk, verbal request in servicedesk"

---

apps.yml

This reverts commit 06e4968fdee6984ecd977a88485722d4734906ac.
Per recent discussion in IAM-1410 this is no longer needed, thus reverting.

Revert "Add infrasec (#825)"

---

apps.yml

Adding mozilliansorg_sre group to AWS

---

apps.yml

Requires a future action to delete `aws_095732026120_poweruser` once all members have accepted their invites.
Jira: [IAM-1460](https://mozilla-hub.atlassian.net/browse/IAM-1460)

Add mozillansorg_sumo-{admins, devs}

---

apps.yml

Jira: [OPS-1470](https://mozilla-hub.atlassian.net/browse/IAM-1470)

Add mozilliansorg_pocket_fin_ops to Pocket's AWS

---

apps.yml

Jira: [IAM-1505](https://mozilla-hub.atlassian.net/browse/IAM-1505), [IAM-1512](https://mozilla-hub.atlassian.net/browse/IAM-1512)
See also:
* mozilla-iam/aws-iam-identity-center-management#22
* mozilla-iam/auth0-deploy#485

Add mozilliansorg_relay_developer (AWS-IT)

---

apps.yml

In particular:
* aws_095732026120_poweruser (completed previously, see 6ba2a5)
* aws_104923852476_admin -> project-guardian-admins
* aws_320464205386_admin -> iam-admins
* aws_320464205386_read_only -> iam-readonly
* aws_359555865025_admin -> webcompat-alexa-admins
* aws_consolidatedbilling_admin -> consolidated-billing-aws (this group existed already, though the membership was different)
* aws_consolidatedbilling_read_only -> consolidated-billing-aws-readonly
* aws_discourse_dev -> created discourse-devs
Jira: [IAM-1460](https://mozilla-hub.atlassian.net/browse/IAM-1460)
See also:
* https://github.com/mozilla-iam/aws-iam-identity-center-management/pull/24
* https://github.com/mozilla-iam/auth0-deploy/pull/486
---

Groups are being migrated to peoplemo

---

apps.yml

IAM-1517: updated access for Fable app; left access group intact should individuals outside moco get invited.

updated fable authorized groups

---

apps.yml

IAM-1489.  Per the last slack convo with Dens, we are going add all the Pan Mozilla teams and not display the tile.

Update tines app

---

apps.yml

Jira: [IAM-1545](https://mozilla-hub.atlassian.net/browse/IAM-1545)

Add AWS access for cloudservices_aws_taskcluster_devs

---

apps.yml

This supports non-moco users having a path to access, notably driving this is a test account.

Add service_jira as an authorized group for Jira products, IAM-1580

---

apps.yml

Adding Springfield (x3) per IAM-1587

---

apps.yml

IAM-1570: decommission Common Voice and associated apps as they are no longer using auth0 IdP. Per dfeller: "We're routing all auth requests to Moz Accounts, so there is no need to keep those entries."

removed voice from auth0

---

apps.yml

We're shutting down the Web SRE Papertrail tenant, so we should remove this entry.
https://mozilla-hub.atlassian.net/browse/OBS-431

remove Web SRE Papetrail entry

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml

This runs pre-commit in gha so if a pre-commit lint issue isn't caught before the devs commit on their localhost, it will catch it here.

Run pre-commit during gha ci/cd

---

.github/workflows/lint-apps.yml
apps.yml
ci/resources/lint-apps-keep-client-ids.yml
requirements.txt
tools/lint-apps

Jira: [IAM-950](https://mozilla-hub.atlassian.net/browse/IAM-950)
This isn't an ideal solution, as discussed previously. But, this aligns with the regular Auth0 administration workflow -- the IT/Infra team can continue to add applications without needing us to intervene.
We lose out on some security by obscurity, but... that might be fine? (Famous last words.)
---
See also:
* https://github.com/mozilla-iam/auth0-deploy/pull/506

Prepare to deny auth if application isn't listed

---

tools/lint-apps

Jira: [IAM-950](https://mozilla-hub.atlassian.net/browse/IAM-950)

ci url output had trailing spaces, which fails yaml linting

---

apps.yml

added 2 new groups to Splunk SC access

---

.github/workflows/tests.yaml
Makefile
README.md
apps.yml
requirements.txt
tests/test_yaml.py
tools/lint-apps

Jira: [IAM-950](https://mozilla-hub.atlassian.net/browse/IAM-950)

Update `make test` to deal with schema change

---

apps.yml

We've swapped domains to www.mozillafoundation.org. This PR updates the sso login url for the mozilla foundation website

Update mozilla foundation sso login url

---

apps.yml

Jira: [OPST-2515](https://mozilla-hub.atlassian.net/browse/OPST-2515)
See also:
* https://github.com/mozilla-iam/aws-iam-identity-center-management/pull/32

Add monitor accounts

---

apps.yml

bug 1707014 added `team_pocket` to egencia/tripactions/navan.  At the time (2021), `team_pocket` was all pocket people, and they were distinct from MoCo/MoFo.  Since then, Pocket is all integrated with MoCo, and as such this team group is unnecessary for Navan.

Remove team_pocket from Navan access

---

apps.yml

IAM-1658: added Vevox-Participants. This is still a PoC. Will rename the other Vevox Admin app if we continue to go with this product.

added vevox-participants app

---

apps.yml

This is a new LDAP group for a legal entity that doesn't exist yet.  But once things get off the ground we'll want them to have access to certain basic apps.
No rush.

Add team_mozorg to basic groups

---

apps.yml

IAM-1691: removed Vevox admin and Vevox participant apps because PoC is over.

removed Vevox admin and participant PoC apps

---

apps.yml

IAM-1693: removed access group used for testing. Udemy-MZLA should be fully onboarded now.

removed testing access group

---

README.md
deploy.sh

This will have to suffice in the mean time, while we revamp this pipeline.
Jira: [IAM-1729](https://mozilla-hub.atlassian.net/browse/IAM-1729)

Disabled webhook builds, so we need a manual trigger

---

README.md

chore: Updates the readme CI badge to show current status of "Main workflow" GitHub Actions pipeline that now is the place to contain "Test Dashboard Configuration / Test Configuration" job/callable and a deployment job after it.
(Also fixes some term casing with no impact on output.)
NB: The workflow name is used for the badge render, so if a different label would be more appropriate, the name key of the workflow file would have to change to bubble up here too.
👓 Preview: [janbrasna/sso-dashboard-configuration#readme](https://github.com/janbrasna/sso-dashboard-configuration/tree/readme-ci#readme)

Update repo badge to current GH CI test results

---

apps.yml

I decom'ed WDE stage a long time ago, and prod 3 months ago.  I missed that there was an SSO component lying around.
Please zap the auth0 apps and the config.  No rush.  Thanks!

Decom WDE, IO-3208
